<?php
/**
 * Auto Generated by ConfigGen
 * !!! DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */

/**
 * 生成代码事例
 */

namespace xxx\yyy\zzz;

final class ConfigGen_market_category_business_服装_category_女装 {

	public $id = 10000000;
	public $logo = '/v2/image/pf/category/1f.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/v2/image/pf/tag/woman/all.jpg',
  ),
  1 => 
  array (
    'name' => '上衣',
    'logo' => '/v2/image/pf/tag/woman/shangyi.jpg',
  ),
  2 => 
  array (
    'name' => '裤子',
    'logo' => '/v2/image/pf/tag/woman/kuzi.jpg',
  ),
  3 => 
  array (
    'name' => '裙子',
    'logo' => '/v2/image/pf/tag/woman/qunzi.jpg',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_服装_category_男装 {

	public $id = 10000001;
	public $logo = '/v2/image/pf/category/2f.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/v2/image/pf/tag/man/all.jpg',
  ),
  1 => 
  array (
    'name' => '上衣',
    'logo' => '/v2/image/pf/tag/man/shangyi.jpg',
  ),
  2 => 
  array (
    'name' => '裤子',
    'logo' => '/v2/image/pf/tag/man/kuzi.jpg',
  ),
  3 => 
  array (
    'name' => 'T恤',
    'logo' => '/public_files/2016/03/09/9ab6e79c4b7741678d31d8fef495eb05.jpg',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_服装_category_童装 {

	public $id = 10000002;
	public $logo = '/v2/image/pf/category/3f.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/v2/image/pf/tag/child/all.jpg',
  ),
  1 => 
  array (
    'name' => '上衣',
    'logo' => '/v2/image/pf/tag/child/shangyi.jpg',
  ),
  2 => 
  array (
    'name' => '裤子',
    'logo' => '/v2/image/pf/tag/child/kuzi.jpg',
  ),
  3 => 
  array (
    'name' => '打底',
    'logo' => '/public_files/2016/02/19/363c4a3a026a355fc4120a6227f95ecb.jpg',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_服装_category_鞋靴 {

	public $id = 10000003;
	public $logo = '/v2/image/pf/category/4f.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/v2/image/pf/tag/shoes/all.jpg',
  ),
  1 => 
  array (
    'name' => '女鞋',
    'logo' => '/v2/image/pf/tag/shoes/nvxie.jpg',
  ),
  2 => 
  array (
    'name' => '男鞋',
    'logo' => '/v2/image/pf/tag/shoes/nanxie.jpg',
  ),
  3 => 
  array (
    'name' => '休闲',
    'logo' => '/v2/image/pf/tag/shoes/xiuxian.jpg',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_服装_category_居家 {

	public $id = 10000004;
	public $logo = '/v2/image/pf/category/5f.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/v2/image/pf/tag/home/all.jpg',
  ),
  1 => 
  array (
    'name' => '内衣',
    'logo' => '/public_files/2016/02/22/76a7abc9682ec90db94e73b1a71d4c37.jpg',
  ),
  2 => 
  array (
    'name' => '文胸',
    'logo' => '/public_files/2016/02/19/04fce975f8851f54de6d19808b25f5e5.jpg',
  ),
  3 => 
  array (
    'name' => '内裤',
    'logo' => '/public_files/2016/02/19/e2909e9cc65bf2a471878b0ab76b0e4b.jpg',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_服装_category {

	public $女装;
	public $男装;
	public $童装;
	public $鞋靴;
	public $居家;

	public function __construct() {
		$this->女装 = new ConfigGen_market_category_business_服装_category_女装;
		$this->男装 = new ConfigGen_market_category_business_服装_category_男装;
		$this->童装 = new ConfigGen_market_category_business_服装_category_童装;
		$this->鞋靴 = new ConfigGen_market_category_business_服装_category_鞋靴;
		$this->居家 = new ConfigGen_market_category_business_服装_category_居家;
	}
}

final class ConfigGen_market_category_business_服装 {

	public $category;

	public function __construct() {
		$this->category = new ConfigGen_market_category_business_服装_category;
	}
}

final class ConfigGen_market_category_business_婴童用品_category_童车 {

	public $logo = '/public_files/2016/04/19/30de5fc900fbf0505fd7ab17d8bdf979.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/4da5032aeb98b6b4d9d0ec358721af1e.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category_玩具 {

	public $logo = '/public_files/2016/04/19/f935cd62080ddb39ef66438b22ae13a0.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/272d5ec96299ff96fb12736847f5f238.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category_母婴用品 {

	public $logo = '/public_files/2016/04/19/d33a5cdf185abc454b60f6ec4ae0d918.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/6234f263c42641b522974fdf619b69e7.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category_母婴食品 {

	public $logo = '/public_files/2016/04/19/a3dd60bf63c3c96bd213ee34623ba5c5.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/dd7d99e822a74bf4c4c0346246000473.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category_幼教用品 {

	public $logo = '/public_files/2016/04/19/ad5ce1eda36bc139c3e40685c503f433.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/a547a207c086771099609ac86b45091b.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category_童装童鞋 {

	public $logo = '/public_files/2016/04/19/f01c69193e56e7ddf1da141a8d9d818a.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/19/6be7dc5d97e806a899b3e9e022b6f457.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_婴童用品_category {

	public $童车;
	public $玩具;
	public $母婴用品;
	public $母婴食品;
	public $幼教用品;
	public $童装童鞋;

	public function __construct() {
		$this->童车 = new ConfigGen_market_category_business_婴童用品_category_童车;
		$this->玩具 = new ConfigGen_market_category_business_婴童用品_category_玩具;
		$this->母婴用品 = new ConfigGen_market_category_business_婴童用品_category_母婴用品;
		$this->母婴食品 = new ConfigGen_market_category_business_婴童用品_category_母婴食品;
		$this->幼教用品 = new ConfigGen_market_category_business_婴童用品_category_幼教用品;
		$this->童装童鞋 = new ConfigGen_market_category_business_婴童用品_category_童装童鞋;
	}
}

final class ConfigGen_market_category_business_婴童用品 {

	public $category;

	public function __construct() {
		$this->category = new ConfigGen_market_category_business_婴童用品_category;
	}
}

final class ConfigGen_market_category_business_综合_category_其他 {

	public $logo = '/public_files/2016/04/18/ff8515d5b8f803d20f81a9c96416c99a.png';
	public $tag = array (
  0 => 
  array (
    'name' => '全部',
    'logo' => '/public_files/2016/04/18/ff8515d5b8f803d20f81a9c96416c99a.png',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_market_category_business_综合_category {

	public $其他;

	public function __construct() {
		$this->其他 = new ConfigGen_market_category_business_综合_category_其他;
	}
}

final class ConfigGen_market_category_business_综合 {

	public $category;

	public function __construct() {
		$this->category = new ConfigGen_market_category_business_综合_category;
	}
}

final class ConfigGen_market_category_business {

	public $服装;
	public $婴童用品;
	public $综合;

	public function __construct() {
		$this->服装 = new ConfigGen_market_category_business_服装;
		$this->婴童用品 = new ConfigGen_market_category_business_婴童用品;
		$this->综合 = new ConfigGen_market_category_business_综合;
	}
}

final class ConfigGen_market_category {

	public $business;

	public function __construct() {
		$this->business = new ConfigGen_market_category_business;
	}
}

final class ConfigGen_market {

	public $category;

	public function __construct() {
		$this->category = new ConfigGen_market_category;
	}
}

final class ConfigGen_route {

	public $default_module = 'order';
	public $default_controller = 'homePage';
	public $default_action = 'index';
	public $default_format = 'html';

	public function __construct() {

	}
}

final class ConfigGen_table_pifa {

	public $mysql_1_default_write = array (
  0 => 'book_lottery',
  1 => 'book_lottery_edit_log',
  2 => 'book_lottery_prize',
  3 => 'book_lottery_user_join',
  4 => 'book_lottery_user_take',
  5 => 'buyer_notice',
  6 => 'entity_certification',
  7 => 'goods_collection_configure',
  8 => 'goods_collection_data',
  9 => 'goods_pf',
  10 => 'labels',
  11 => 'labels_business_relation',
  12 => 'labels_goods_relation',
  13 => 'labels_mapping',
  14 => 'market',
  15 => 'market_category',
  16 => 'category',
  17 => 'market_category_tag',
  18 => 'market_edit_log',
  19 => 'market_goods',
  20 => 'market_goods_category_tag_relation',
  21 => 'market_offline',
  22 => 'market_range',
  23 => 'market_shop',
  24 => 'market_shop_ban',
  25 => 'market_tag_shop_relation',
  26 => 'market_version',
  27 => 'member_apply',
  28 => 'member_area',
  29 => 'member_invite',
  30 => 'member_log',
  31 => 'notice_category',
  32 => 'qualification_certification',
  33 => 'rule_team_relation',
  34 => 'scratch_card',
  35 => 'scratch_card_edit_log',
  36 => 'scratch_card_prize',
  37 => 'scratch_card_user_join',
  38 => 'scratch_card_user_take',
  39 => 'shop_common_notice',
  40 => 'shop_notice',
  41 => 'tag',
  42 => 'task_wxhb',
  43 => 'team_advertisement',
  44 => 'team_pf',
  45 => 'team_score',
  46 => 'team_score_record',
  47 => 'ump_guide_marketing',
  48 => 'ump_member_discount_join_log',
  49 => 'ump_time_limited_discount',
  50 => 'ump_time_limited_discount_goods_join',
  51 => 'ump_time_limited_discount_join_log',
  52 => 'user_follow',
  53 => 'user_goods_record',
  54 => 'user_select',
  55 => 'user_shop_record',
  56 => 'shop_invitation_list',
  57 => 'shop_invitation_model',
  58 => 'goods_topic_activity',
  59 => 'shop_recommend',
);

	public function __construct() {

	}
}

final class ConfigGen_table {

	public $pifa;

	public function __construct() {
		$this->pifa = new ConfigGen_table_pifa;
	}
}

final class ConfigGen_version {

	public $permission = array (
  1 => 
  array (
    'id' => 1,
    'name' => 'shop_num',
    'store_field' => 'shop_num',
    'field_set' => 'shop_num',
    'des' => '市场店铺数限制',
  ),
  2 => 
  array (
    'id' => 2,
    'name' => 'start_time',
    'store_field' => 'start_time',
    'field_set' => 'start_time',
    'des' => '版本开始时间',
  ),
  3 => 
  array (
    'id' => 3,
    'name' => 'end_time',
    'store_field' => 'end_time',
    'field_set' => 'end_time',
    'des' => '版本结束时间',
  ),
  4 => 
  array (
    'id' => 4,
    'name' => 'test',
    'store_field' => 'identifier',
    'field_set' => 0,
    'des' => '开发的测试字段，上线干掉',
  ),
  5 => 
  array (
    'id' => 5,
    'name' => 'default',
    'store_field' => 'config_set',
    'field_set' => 'default',
    'des' => 'config的测试写法，上线会干掉',
  ),
);
	public $version = array (
  1 => 
  array (
    'id' => 1,
    'name' => '内部测试版本',
    'info' => '内部测试版是专门给测试人员使用的版本，只允许加入10家店铺',
    'shop_num' => 100,
    'identifier' => 0,
    'config_set' => '{}',
  ),
  2 => 
  array (
    'id' => 1,
    'name' => '临时自定义版本',
    'info' => '前期不能确定版本分层的情况下，暂时使用的测试版本',
    'shop_num' => 500,
    'identifier' => 0,
    'config_set' => '{}',
  ),
);

	public function __construct() {

	}
}

final class ConfigGen_connection_elasticsearch_market_shop {

	public $engine = 'es';
	public $hosts = array (
  0 => 'pf.searchapi.youzan.com:80',
);

	public function __construct() {

	}
}

final class ConfigGen_connection_elasticsearch_market_goods {

	public $engine = 'es';
	public $hosts = array (
  0 => 'pf.searchapi.youzan.com:80',
);

	public function __construct() {

	}
}

final class ConfigGen_connection_elasticsearch {

	public $market_shop;
	public $market_goods;

	public function __construct() {
		$this->market_shop = new ConfigGen_connection_elasticsearch_market_shop;
		$this->market_goods = new ConfigGen_connection_elasticsearch_market_goods;
	}
}

final class ConfigGen_connection_http_default {

	public $engine = 'http';
	public $pool = array (
);

	public function __construct() {

	}
}

final class ConfigGen_connection_http {

	public $default;

	public function __construct() {
		$this->default = new ConfigGen_connection_http_default;
	}
}

final class ConfigGen_connection_mysql_default_write_pool {

	public $maximum_1_connection_2_count = '50';
	public $minimum_1_connection_2_count = '10';
	public $heartbeat_1_time = 35000;
	public $init_1_connection = '5';

	public function __construct() {

	}
}

final class ConfigGen_connection_mysql_default_write {

	public $engine = 'mysqli';
	public $host = '10.200.175.98';
	public $user = 'user_pifa';
	public $password = 'U83niFfcE1ZVGCrqCpfP';
	public $database = 'pifa';
	public $port = 1000;
	public $pool;

	public function __construct() {
		$this->pool = new ConfigGen_connection_mysql_default_write_pool;
	}
}

final class ConfigGen_connection_mysql_default_read {

	public $engine = 'mysqli';
	public $pool = array (
);

	public function __construct() {

	}
}

final class ConfigGen_connection_mysql {

	public $default_write;
	public $default_read;

	public function __construct() {
		$this->default_write = new ConfigGen_connection_mysql_default_write;
		$this->default_read = new ConfigGen_connection_mysql_default_read;
	}
}

final class ConfigGen_connection_redis_default_write_pool {

	public $maximum_1_connection_2_count = '50';
	public $minimum_1_connection_2_count = '10';
	public $keeping_1_sleep_2_time = '10';
	public $init_1_connection = '2';

	public function __construct() {

	}
}

final class ConfigGen_connection_redis_default_write {

	public $engine = 'redis';
	public $host = '127.0.0.1';
	public $port = 6602;
	public $pool;

	public function __construct() {
		$this->pool = new ConfigGen_connection_redis_default_write_pool;
	}
}

final class ConfigGen_connection_redis {

	public $default_write;

	public function __construct() {
		$this->default_write = new ConfigGen_connection_redis_default_write;
	}
}

final class ConfigGen_connection_tcp_trace_config {

	public $open_length_check = 1;
	public $package_length_type = 'N';
	public $package_length_offset = 0;
	public $package_body_offset = 0;
	public $open_nova_protocol = 1;

	public function __construct() {

	}
}

final class ConfigGen_connection_tcp_trace_pool {

	public $keeping_1_sleep_2_time = 10000;
	public $init_1_connection = 2;

	public function __construct() {

	}
}

final class ConfigGen_connection_tcp_trace {

	public $engine = 'tcp';
	public $host = '10.200.181.71';
	public $port = '2280';
	public $timeout = 5000;
	public $hasRecv = false;
	public $config;
	public $pool;

	public function __construct() {
		$this->config = new ConfigGen_connection_tcp_trace_config;
		$this->pool = new ConfigGen_connection_tcp_trace_pool;
	}
}

final class ConfigGen_connection_tcp {

	public $trace;

	public function __construct() {
		$this->trace = new ConfigGen_connection_tcp_trace;
	}
}

final class ConfigGen_connection {

	public $elasticsearch;
	public $http;
	public $mysql;
	public $redis;
	public $tcp;

	public function __construct() {
		$this->elasticsearch = new ConfigGen_connection_elasticsearch;
		$this->http = new ConfigGen_connection_http;
		$this->mysql = new ConfigGen_connection_mysql;
		$this->redis = new ConfigGen_connection_redis;
		$this->tcp = new ConfigGen_connection_tcp;
	}
}

final class ConfigGen_haunt_discovery {

	public $host = '10.10.138.48';
	public $port = 2379;
	public $timeout = 30000;
	public $uri = '/v2/keys';
	public $protocol = 'nova';
	public $namespace = 'com.youzan.service';
	public $loop_time = 1000;

	public function __construct() {

	}
}

final class ConfigGen_haunt_watch {

	public $host = '10.10.138.48';
	public $port = 2379;
	public $timeout = 30000;
	public $uri = '/v2/keys';
	public $protocol = 'nova';
	public $namespace = 'com.youzan.service';
	public $loop_time = 5000;

	public function __construct() {

	}
}

final class ConfigGen_haunt_watch_store {

	public $loop_time = 1000;

	public function __construct() {

	}
}

final class ConfigGen_haunt_register {

	public $host = '127.0.0.1';
	public $port = 8687;
	public $uri = '/register';
	public $timeout = 30000;
	public $protocol = 'nova';
	public $namespace = 'com.youzan.service';

	public function __construct() {

	}
}

final class ConfigGen_haunt {

	public $app_names = array (
);
	public $discovery;
	public $watch;
	public $watch_store;
	public $register;

	public function __construct() {
		$this->discovery = new ConfigGen_haunt_discovery;
		$this->watch = new ConfigGen_haunt_watch;
		$this->watch_store = new ConfigGen_haunt_watch_store;
		$this->register = new ConfigGen_haunt_register;
	}
}

final class ConfigGen_hawk {

	public $run = true;
	public $host = 'api.hawk.qima-inc.com';
	public $port = 80;
	public $uri = '/monitor/push';
	public $time = 60000;

	public function __construct() {

	}
}

final class ConfigGen_monitor_trace {

	public $run = true;

	public function __construct() {

	}
}

final class ConfigGen_monitor {

	public $trace;

	public function __construct() {
		$this->trace = new ConfigGen_monitor_trace;
	}
}

final class ConfigGen_nova_client_config {

	public $open_length_check = 1;
	public $package_length_type = 'N';
	public $package_length_offset = 0;
	public $package_body_offset = 0;
	public $open_nova_protocol = 1;

	public function __construct() {

	}
}

final class ConfigGen_nova_client {

	public $host = '127.0.0.1';
	public $port = '10002';
	public $timeout = 15;
	public $persistent = true;
	public $config;

	public function __construct() {
		$this->config = new ConfigGen_nova_client_config;
	}
}

final class ConfigGen_nova_novaApi {

	public $path = 'vendor/nova-service/pf-api/gen-php';
	public $namespace = 'Com\\Youzan\\Pf\\';

	public function __construct() {

	}
}

final class ConfigGen_nova_platform {

	public $collect_listen_host = '127.0.0.1';
	public $collect_listen_port = 8181;

	public function __construct() {

	}
}

final class ConfigGen_nova {

	public $client;
	public $novaApi;
	public $platform;

	public function __construct() {
		$this->client = new ConfigGen_nova_client;
		$this->novaApi = new ConfigGen_nova_novaApi;
		$this->platform = new ConfigGen_nova_platform;
	}
}

final class ConfigGen_server_config {

	public $worker_num = 2;
	public $dispatch_mode = 3;
	public $max_request = 100000;
	public $reactor_num = 1;
	public $open_length_check = 1;
	public $package_length_type = 'N';
	public $package_length_offset = 0;
	public $package_body_offset = 0;
	public $open_nova_protocol = 1;
	public $package_max_length = 200000;

	public function __construct() {

	}
}

final class ConfigGen_server_monitor {

	public $max_request = 100000;
	public $max_live_time = 1800000;
	public $check_interval = 10000;
	public $memory_limit = 1610612736;
	public $cpu_limit = 70;

	public function __construct() {

	}
}

final class ConfigGen_server {

	public $host = '0.0.0.0';
	public $port = '8000';
	public $config;
	public $monitor;

	public function __construct() {
		$this->config = new ConfigGen_server_config;
		$this->monitor = new ConfigGen_server_monitor;
	}
}

final class ConfigGen {

	public $market;
	public $route;
	public $table;
	public $version;
	public $connection;
	public $haunt;
	public $hawk;
	public $monitor;
	public $nova;
	public $server;

	public function __construct() {
		$this->market = new ConfigGen_market;
		$this->route = new ConfigGen_route;
		$this->table = new ConfigGen_table;
		$this->version = new ConfigGen_version;
		$this->connection = new ConfigGen_connection;
		$this->haunt = new ConfigGen_haunt;
		$this->hawk = new ConfigGen_hawk;
		$this->monitor = new ConfigGen_monitor;
		$this->nova = new ConfigGen_nova;
		$this->server = new ConfigGen_server;
	}
}

return new ConfigGen;